### ISSUE TITLE
Enable HEX code input in modal window

### ISSUE THREAD

**Issue by nfiser** [isarvindone/figma-matercolor#2]
I cannot input the HEX code directly in the modal window. I have to use the color picker, which sometimes tends to get the color value wrong, or I have to first switch from RGB to HSL and then to HEX to get to the input. If I could insert the HEX code into this field directly, that would be real awesome!
![Matercolor](https://user-images.githubusercontent.com/90031703/131975252-3ed9f4e1-52e5-4dc3-b746-0f5abb768959.png)

Anyways, thanks for your contribution to the Figma community.

Regards,
Norman

**Comment by isarvindone** [comment]
@nfiser Resolved in the latest release! You can check it out.
