### ISSUE TITLE
Create only one layer when adding colors to the styles panel

### ISSUE THREAD

**Issue by nfiser** [isarvindone/figma-matercolor#3]
Currently when I generate a color palette and select the option "Generate paint styles for palette", this adds several layers in my styles panel. It would be better to generate only one layer by default, and add sublayers if users would use the "/" symbol between names.

Currently:
![image](https://user-images.githubusercontent.com/90031703/132167648-a8c047da-068a-4d92-b740-9eca50526897.png)

Suggested:
![image](https://user-images.githubusercontent.com/90031703/132167970-e96f6ad2-524f-4ea6-b987-7d2c5e87837b.png)

![image](https://user-images.githubusercontent.com/90031703/132167686-2fe2ddb2-a2b6-4e73-8802-cace4b5bd651.png)

You could also add a supportive text below the input field, saying that "/" will create sublayers/subfolders.

Would also suggest using an outlined style for the input field (similar to what Figma uses in the Share modal). This would better indicate its clickability.

![image](https://user-images.githubusercontent.com/90031703/132167866-5bf2c966-6af3-41c1-a161-7ad8afde41c5.png)

**Comment by isarvindone** [comment]
@nfiser Resolved in the latest release! You can check it out.
